In [2]:
import json
import numpy as np
import tensorflow as tf

from sklearn.manifold import TSNE
from sklearn.decomposition import PCA

In [4]:
with open('labels.json','r') as fp:
    labels = json.load(fp)

In [5]:
embeddings = np.load('embeddings.npy')

In [6]:
embeddings.shape

(2500, 100)

In [7]:
labels[:10]

['UNK', 'D5', 'A4', 'E5', 'G5', 'C5', 'G4', 'D4', 'F5', 'A5']

In [101]:
def gen_interesting_labels(base):
    for i in range(12):
        new_chord = sorted(map(lambda x: (x+i) % 12, base))
        yield str(new_chord).replace(" ", "")

In [102]:
gen_major = gen_interesting_labels([0, 4, 7])

In [103]:
majors = [x for x in gen_major if x in labels]

In [104]:
majors

['[0,4,7]',
 '[1,5,8]',
 '[2,6,9]',
 '[3,7,10]',
 '[4,8,11]',
 '[0,5,9]',
 '[1,6,10]',
 '[2,7,11]',
 '[0,3,8]',
 '[1,4,9]',
 '[2,5,10]',
 '[3,6,11]']

In [113]:
tsne = TSNE(perplexity=30, n_components=2, init='pca', n_iter=5000)
pca = PCA(n_components=2)

low_dim_embs = tsne.fit_transform(embeddings)

In [114]:
majors_emb = [low_dim_embs[labels.index(l)] for l in majors]

In [115]:
majors_emb

[array([-6.17088729, -0.36583235]),
 array([-6.68684941,  2.777555  ]),
 array([-5.4702702 , -0.69882808]),
 array([-7.14347796,  2.07427591]),
 array([-7.65004886, -1.59685044]),
 array([-6.24737837,  0.33915999]),
 array([-4.97746055, -3.47585036]),
 array([-5.11461879,  0.47082713]),
 array([-7.37698821,  3.36951418]),
 array([-7.01884124, -1.29100429]),
 array([-6.39711904,  1.18678636]),
 array([-7.12620255, -1.56928813])]

In [116]:
p = figure(title="Major triads in embedding space")

In [117]:
xs = [xy[0] for xy in majors_emb]
ys = [xy[1] for xy in majors_emb]

In [118]:
ys

[-0.36583235036971573,
 2.7775550006379852,
 -0.69882808207711722,
 2.0742759138333309,
 -1.5968504446242788,
 0.33915998555903099,
 -3.4758503559525811,
 0.47082713095301765,
 3.3695141804291349,
 -1.2910042897118423,
 1.186786359531192,
 -1.5692881264911465]

In [119]:
p.scatter(x=xs, y=ys)

In [120]:
show(p)